docs: bump example value to v4
nrkno/github-workflow-terraform-config pull request #92
Opened 2023-03-02 13:53 UTC by stigok

2023-03-02 13:53 UTC, WilliamDahlen approved these changes

2023-03-06 08:20 UTC, umglurf requested changes

2023-03-06 21:06 UTC, stigok commented on README.md
> +uses: nrkno/github-workflow-terraform-config/.github/workflows/workflow.yaml@v4
Agreed!

2023-03-07 07:10 UTC, umglurf approved these changes

2023-03-07 08:04 UTC, siljekristensen approved these changes

2023-03-16 09:38 UTC, merged